app.security.dev-secret=w1kGqtsaL6XKa73TkDwSFRnrSm0ps7rXbus36GHVTQY=
spring.datasource.url=jdbc:h2:mem:padelapp
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
